apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini-crm-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mini-crm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mini-crm-service
                port:
                  number: 80
